CREATE TABLE IF NOT EXISTS category (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(5000) NOT NULL,
  `is_active` BIT NOT NULL DEFAULT TRUE,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;