CREATE TABLE quiz (
  id BIGINT NOT NULL AUTO_INCREMENT,
   title VARCHAR(255) NOT NULL,
   description VARCHAR(5000) NOT NULL,
   max_marks VARCHAR(255) NOT NULL,
   number_of_questions VARCHAR(255) NOT NULL,
   is_active BIT NOT NULL DEFAULT TRUE,
   created_by VARCHAR(255) NOT NULL,
   created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   category_id BIGINT NOT NULL,
   CONSTRAINT pk_quiz PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;

ALTER TABLE quiz ADD CONSTRAINT FK_QUIZ_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);