CREATE TABLE question (
  id BIGINT NOT NULL AUTO_INCREMENT,
   content VARCHAR(5000) NOT NULL,
   image VARCHAR(255) NULL,
   option1 VARCHAR(500)  NULL,
   option2 VARCHAR(500)  NULL,
   option3 VARCHAR(500)  NULL,
   option4 VARCHAR(500)  NULL,
   answer VARCHAR(500) NOT NULL,
   type VARCHAR(255) NOT NULL,
   is_active BIT NOT NULL DEFAULT TRUE,
   created_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   quiz_id BIGINT NULL,
   CONSTRAINT pk_question PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARACTER SET = utf8;

ALTER TABLE question ADD CONSTRAINT FK_QUESTION_ON_QUIZ FOREIGN KEY (quiz_id) REFERENCES quiz (id);