flyway.url: jdbc:mysql://localhost:3306/exam?autoReconnect=true&useSSL=false&useUnicode=true&activationRemindersSentBy=utf8
flyway.user: root
flyway.password: root
flyway.locations: filesystem:migrations
flyway.enabled: true

spring:
  application:
    name: Exam
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?autoReconnect=true&useSSL=false&useUnicode=true&activationRemindersSentBy=utf8
    username: root
    password: root